### ISSUE TITLE
Capture debugee output

### ISSUE THREAD

**Issue by vivi00790** [cs01/pygdbmi#28]
Gdbmi seems not capturing debugee output (like printf)
This may lead to timeout error
I wrote a simple program that print a string per second for 10 seconds and set two breakpoints at the start and end of loop.
Gdbmi works fine until gdb hit the first break point, however after I type continue, debugee will enter the
10 seconds loop, then cause gdbmi timeout error and never hit second bp at the loop end.
 this loop will print output properly in gdb with --interpreter=mi2
Do you have any suggestion? Or should I edit timeout limit depends on debugee?

**Comment by cs01** [comment]
Hi, thanks for the question. This happens because gdb is run as a subprocess, which causes event handling for new data to stdout/stderr to become less reliable.

There are a few options, you can can experiment with them and see which help
* interrupt gdb with the [`interrupt_gdb` method](https://grassfedcode.com/pygdbmi/api/pygdbmi.html#pygdbmi.gdbcontroller.GdbController.interrupt_gdb) of the GdbController class
* force flush output check for output with `-data-evaluate-expression fflush(0)` or `call fflush(0)`. I think this needs to be run after interrupting.
* periodically call the [`get_gdb_response` method](https://grassfedcode.com/pygdbmi/api/pygdbmi.html#pygdbmi.gdbcontroller.GdbController.get_gdb_response) of the GdbController class, with `raise_error_on_timeout=False`. Similar to the previous bullet, you may have to interrupt gdb before running this.

Let me know if you get it to work.

**Comment by vivi00790** [comment]
sorry for the late reply
i've tried the way above a bit and i got some more question
in my debugee some commands need more than one seconds(defalt value of gdbController.write()) to execute, and this will also cause GdbTimeoutError 
my question is: if i don't clearly know the command execute time, should i have to perform the way above (periodcally interrupt then get_gdb_response) on every command i entered? If so, is it possible that this method will cause some synchronization problems in the debugee?

**Comment by cs01** [comment]
You shouldn't have to do it for every single method. For example, you can do

`get_gdb_response(timeout_sec=10)` if you know the command can take up to 10 seconds.

You could also do `get_gdb_response(raise_error_on_timeout=False)` if you don't care about the output for some reason.
